# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZFOVl1hGWl-43FaQXoXkKLie8lrHKPX
"""

def fib(n):
    if n ==0:
        return n
    elif n==1:
        return n
    else:
        return fib(n-1)+fib(n-2)
for n in range(20):
  print(fib(n))
