# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZFOVl1hGWl-43FaQXoXkKLie8lrHKPX
"""
def fib(n):
    for i in range(0,n+1):
        if i ==0:
            t0=0
            t1=0
            t2=0
        elif i==1:
            to=0
            t1=1
            t2=1
        else:
            t2=t0+t1
            t0=t1
            t1=t2
    return t2
for n in range(20):
    print(fib(n))


